version: '3'
services:
  m_web:
    build:
      context: ./images/php
    container_name: m_web
    restart: always
    user: application
    environment:
      - WEB_ALIAS_DOMAIN=local.domain.com
      - WEB_DOCUMENT_ROOT=/app/pub
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=3048M
      - PHP_MAX_EXECUTION_TIME=700
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - COMPOSER_VERSION=1
      - POSTFIX_RELAYHOST=[mailhog]:1025
      - XDEBUG_REMOTE_PORT=9000
    volumes:
      - ${VOLUME_DIR}:/app:cached
    ports:
      - "443:443"
      - "32823:22"
    links:
      - m_mysql
  m_mysql:
    image: mariadb:10
    container_name: m_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
    volumes:
      - db-data:/var/lib/mysql
  m_phpmyadmin:
    container_name: m_phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    links:
      - m_mysql:db
    depends_on:
      - m_mysql
  mailhog:
    image: mailhog/mailhog
    container_name: m_mail
    environment:
      - VIRTUAL_HOST=mail.docker
      - VIRTUAL_PORT=8025
    ports:
      - "8025:8025"

volumes:
  db-data:
    external: false
